// <auto-generated />
namespace G9VN.TIKTAK.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addRelationshipsItemOptionVSStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRelationshipsItemOptionVSStock));
        
        string IMigrationMetadata.Id
        {
            get { return "201712260458179_addRelationshipsItemOptionVSStock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
