// <auto-generated />
namespace G9VN.TIKTAK.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_datatype_PurchaseInvoiceDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_datatype_PurchaseInvoiceDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070347034_edit_datatype_PurchaseInvoiceDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
