// <auto-generated />
namespace G9VN.TIKTAK.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Description_SaleInvoice_PurchaseInvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Description_SaleInvoice_PurchaseInvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201803260201290_add_Description_SaleInvoice_PurchaseInvoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
