// <auto-generated />
namespace G9VN.TIKTAK.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addColumn_DiscountReason_inPurchaseInvoice_SaleInvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumn_DiscountReason_inPurchaseInvoice_SaleInvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201805180230230_addColumn_DiscountReason_inPurchaseInvoice_SaleInvoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
